version: '3.9'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql-ventas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ventas_autos
    volumes:
      - ./Dump20251026:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./ventas-autos
    container_name: backend-ventas
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ventas_autos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"

  frontend:
    build: ./ventas-autos-frontend
    container_name: frontend-ventas
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
